name: quarto
dependencies:
  - python=3.7
  - pip=19.2.3
  - pytest=5.2.1
  - numpy=1.16.5
  - jupyter=1.0.0
  - pandas=0.25.3
  - pytorch::pytorch=1.3.1
  - pytorch::cpuonly=1.0.0
  - pip:
      - pyarrow==0.15.1
      - google-cloud-storage==1.21.0
      - python-digitalocean==1.14.0
      - python-dotenv==0.10.3
